export const {
	REACT_APP_PROTOCOL = 'http:',
	REACT_APP_HOST = '192.168.0.105',
	REACT_APP_ION_PORT = 5551,
	REACT_APP_SERVER_PORT = 4000
} = process.env;

export const ION_SERVER = `${REACT_APP_PROTOCOL}//${REACT_APP_HOST}:${REACT_APP_ION_PORT}`;

export const BASE_URL = `${REACT_APP_PROTOCOL}//${REACT_APP_HOST}:${REACT_APP_SERVER_PORT}`;
